### ISSUE TITLE
Request: Provide a way to retrieve the versionCode and versionName used in the last build

### ISSUE THREAD

**Issue by TylerMcCraw** [ReactiveCircus/app-versioning#2]
It would be helpful to provide another 2 Gradle tasks to get the versionCode and versionName of the last build.
In my use case, our CI process will send a notification (via Slack message) to our team about new builds upon a successful CI release. This notification sends information including the versionCode and versionName.
In order to help me integrate this into our current process, I'd need a way to fetch these two values.

This may be a little tricky, implementation-wise, because if the versionCode was generated using a timestamp, you can't simply call the `generateAppVersionInfoFor` Gradle task again since it would be a new timestamp at that point.
So, there would need to be some way of caching these values.
Or if you know of a way to fetch these using standard Gradle tasks, that'd be great to know!

**Comment by TylerMcCraw** [comment]
It looks like you're actually already caching this to versionCodeFile and versionNameFile which use the output directory.
So if there were just a couple gradle tasks to fetch these values, then that would help me out a ton!

**Comment by ychescale9** [comment]
AFAIK the source of truth for `versionCode` and `versionName` in the Gradle / AGP world is the final merged manifest. So we could potentially write a task that parses the manifest file the prints the versionCode / versionName to the console - [here's a skeleton](https://github.com/android/gradle-recipes/blob/master/BuildSrc/manifestReplacementTest/buildSrc/src/main/kotlin/VerifyManifestTask.kt).

You could also write a script to use the `aapt` binary in the Android SDK to extract the versionCode and versionName [but it's not as nice](https://stackoverflow.com/a/55010681).

The important thing to note is that `version_code` and `version_name` files produced by the `GenerateAppVersionInfo` task is not necessarily the final versionCode and versionName that get injected into the merged manifest, as other plugins **can** overwrite them.

However with most of the CI use cases like the one you mentioned it's probably ok to trust the `version_code` and `version_name` outputs produced by this plugin 😅  as long as you don't have other plugins / tasks that overwrites the manifest file at a later stage of the build lifecycle.

If that's the case, [this](https://github.com/ReactiveCircus/streamlined/blob/5fcdd183bf7edfc73c1e7793857952e518e30b60/.github/workflows/ci.yml#L195-L219) is what I do currently to cat the output of those files into a var: `VERSION_CODE=$(cat app/build/outputs/app_versioning/prodRelease/version_code.txt)`. You just need to make sure that these build output files are archived and shared with the job that needs it if you assmble the APK and do this kind of stuff in separate VMs in your CI pipeline, so you can avoid re-running the `generateAppVersionInfo` task which might produces different result like you pointed out.

Maybe we should include this info in a recipe section.

**Comment by TylerMcCraw** [comment]
I see you included this info in the README.
Feel free to close out the issue.
