### ISSUE TITLE
about auto increment version code

### ISSUE THREAD

**Issue by kennir** [ReactiveCircus/app-versioning#23]
I want an auto-increment number as version code, It should automatically increment by 1 for each release build, what are the best practice for app-versioning?  write a wrapper ? or override overrideVersionCode function?

Thanks

**Comment by ychescale9** [comment]
app-versioning uses git info to generate versionCode.

Auto incrementing the versionCode for each release means the source of the versionCode has nothing to do with git, so you'll need to keep track of this versionCode yourself and decide when to increment it, where to store it etc, and inject it as environment variable and read it from `overrideVersionCode`.

**Comment by kennir** [comment]
Thanks for reply
