### ISSUE TITLE
overrideVersionCode and overrideVersionName lambdas not called when there are no tags in the repo

### ISSUE THREAD

**Issue by julioromano** [ReactiveCircus/app-versioning#25]
I have a repo without tags and need to get the SemVer string (i.e. `1.2.3`) from env vars.

I can access the env vars from the `providers` argument in the `overrideVersionCode` and `overrideVersionName` lambdas but it seems they are never called when the repo has no tags:
It prints the error `No git tags found. Falling back to version code 0 and version name "".` and the build fails with `Version code not found in manifest.`.

I understand this is somehow an odd use of this plugin. But it would be useful if it was supported.

Would it be possible to call those lambdas anyways (or support this use case in any other way)?

**Comment by ychescale9** [comment]
In that case there's not much this plugin can provide. You can use the new AGP Variant APIs and do something like this in your `app/build.gradle.kts`:

```
androidComponents {
    onVariants { variant ->
        val mainOutput = variant.outputs.single {
            it.outputType == com.android.build.api.variant.VariantOutputConfiguration.OutputType.SINGLE
        }
        val versionCode = providers
            .environmentVariable("VERSION_CODE")
            .forUseAtConfigurationTime()
            .map { it.toInt() }
            .getOrElse(1)
        val versionName = providers
            .environmentVariable("VERSION_NAME")
            .forUseAtConfigurationTime()
            .getOrElse("1.0")
        mainOutput.versionCode.set(versionCode)
        mainOutput.versionName.set(versionName)
    }
}
```

**Comment by julioromano** [comment]
Super! Thank you very much for the help!
