### ISSUE TITLE
Cannot fingerprint input property 'kotlinVersionCodeCustomizer': value '(GitTag, ProviderFactory, VariantInfo) -> kotlin.Int' cannot be serialized.

### ISSUE THREAD

**Issue by mr3y-the-programmer** [ReactiveCircus/app-versioning#33]
I'm getting the following error when running `./gradlew generateAppVersionInfoFor<Variant>` with gradle configuration cache disabled.
```
> Cannot fingerprint input property 'kotlinVersionCodeCustomizer': value '(io.github.reactivecircus.appversioning.GitTag, org.gradle.api.provider.ProviderFactory, io.github.reactivecircus.appversioning.VariantInfo) -> kotlin.Int' cannot be serialized.
```
And I'm getting the following 2 errors when running `./gradlew generateAppVersionInfoFor<Variant>` with gradle configuration cache enabled. the first error is the aforementioned one, and the the second one is:
```
1 problem was found storing the configuration cache.
- Task `:app:generateAppVersionInfoFor<Variant>` of type `io.github.reactivecircus.appversioning.tasks.GenerateAppVersionInfo`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```
I thought that configuration cache problems were addressed at #24, but even when the configuration cache is disabled, the build still fails with the first error above.

Steps to reproduce:
app-versioning: 1.3.1
Gradle: 8.2.1
AGP: 8.1.0
`appVersioning` extension configuration in my app's `build.gradle.kts`:
```
appVersioning {
    overrideVersionCode { _, _, _ ->
        extensions.getByType<ApplicationExtension>().defaultConfig.versionCode!! + 1
    }
}
```
Run generateAppVersionInfo for any variant, for example `debug`: `./gradlew generateAppVersionInfoForDebug`

**Additional Context**:
I reproduced it on my side project https://github.com/mr3y-the-programmer/Ludi as I was trying to automate the release process for it.

**Comment by mr3y-the-programmer** [comment]
My Use case is increasing the `versionCode` property by 1 on each release, this is why I used `extensions` to get the current `versionCode` but this is not strictly required, if that defeats the purpose of computing the version code lazily, I can avoid it and I think I will compute the `versionCode` using only the 3 parameters as you mentioned Thanks.

**Comment by mr3y-the-programmer** [comment]
Follow up: After computing `versionCode` lazily, running `generateAppVersionInfoFor<Variant>` completes successfully without errors.

**Comment by VitaSokolova** [comment]
Could you show a code snippet how did you "compute `versionCode` lazily"?
