### ISSUE TITLE
Customization of git describe match pattern

### ISSUE THREAD

**Issue by Wrywulf** [ReactiveCircus/app-versioning#6]
Hi,

I build several applications from the same git repo. All applications must be versioned independently, but still by using git tags.

Currently, the app-versioning plugin only allows processing the latest git tag, which wouldn't work in my setup.

Is there a possibility that users of the plugin could get a hook into the parameters for `git describe`? Specifically, providing the `--match ` glob pattern.

Being able to add a match pattern would allow me to single-out the relevant application-specific git tag.

I know this is probably a niche use case, but I see that the support is almost there. `GitClient` offers the functionality already:

```
    fun describeLatestTag(pattern: String? = null): String? {
        val command = buildList {
            add("git")
            add("describe")
            if (pattern != null) {
                add("--match")
                add(pattern)
            }
            add("--tags")
            add("--long")
        }
        return runCatching { command.execute(projectDir) }.getOrNull()
    }
```
but `describeLatestTag` is currently invoked without args.

**Comment by ychescale9** [comment]
Tag matching is something I explored a little bit but decided to hold until I come across some real use cases. This is a great use case!

In the original version I was using the `--match` pattern to find the latest tag that *looks like* a SemVer, but that was insufficient as I needed a fully SemVer compliant tag to extract the components, or force user to use `overrideVersionCode` to compute versionCode if the tag isn't SemVer.

I can explore adding the `match` pattern to the plugin configuration which seems to be a reasonable way to opt-in to the custom tag filtering behavior.

BTW can you share how you define different tags for multiple applications? in other words what `--match` pattern would you use to find the tag for one application?

Another use case I can imagine is having a single application module with multiple product flavors to build multiple applications, in which case the plugin is only applied once and so we need a way to specify different `match` pattern based on the build variant.

```kotlin
appVersioning {
  overrideVersionCode { gitTag, providers ->
    ...
  }
  tagFilter { variantName ->
    when (variantName) {
      "paidRelease" -> <pattern1>
      "freeRelease" -> <pattern2>
      ...
    }
  }
}
```

Any thoughts?

**Comment by Wrywulf** [comment]
Appreciate the feedback.

>BTW can you share how you define different tags for multiple applications? in other words what --match pattern would you use to find the tag for one application?

Still in early stages, but my current plan is to define a custom "app identifier" and let that be part of the semver build meta data section (https://semver.org/#spec-item-10).

So, something like: `1.5.7+<app identifier>`. 
Don't exactly know what to use as an app identifier yet, but ofc it has to be unique in the repo.. and immutable once declared :)

I guess a glob match pattern could be something like "[0-9].[0-9].[0-9]*+<app identifier>*" for that. Haven't tried yet, but something could like that.


Regarding the multiple flavors -> multiple applications:
I guess it depends on if you really need the flavors to be versioned and released independently. But yeah, something like what you propose on a per-variant basis could work I guess.

As an aside, I could see that accessing the current variant in the `overrideVersion<Name|Code>` lambda would be useful.

I have some rules around versionName based on the variant info. For example, if the variant is not a "production" flavor and "release" build type I add extra information to the versionName such as commit hash and commits-since-tag. If the variant is production release, all this information is not included and the versionName is plain major.minor.patch.

**Comment by Wrywulf** [comment]
+1 for:
> I can explore adding the match pattern to the plugin configuration which seems to be a reasonable way to opt-in to the custom tag filtering behavior.

btw :)

**Comment by ychescale9** [comment]
Thanks for the feedback. I've wanted to add build variant info to the `overrideVersion<Code|Name` lambdas for a while but kind of been waiting for someone else to propose it so I know there are actual use cases:)

I'll play with tag filtering in both your multiple app modules and the single app multiple flavor setups to see how it works in practice.

I may reach out at some point to get your feedback as I don't have many real projects to battle test the plugin for all the use cases it supports and the best I can do is simulate different ways of consuming the plugin in integration tests:)

**Comment by Wrywulf** [comment]
No probs, happy to help out if I can.

Just reach out when/if you need some early feedback.

**Comment by Wrywulf** [comment]
@ychescale9 Do you need any help in getting this issue resolved?

**Comment by ychescale9** [comment]
I got most of the work done but have been procrastinating writing tests😅.

If you don't mind could you share some of your tag patterns you intend to use in your project so I can write some integration tests to make sure your cases are covered?

BTW this is all going to require AGP 4.0.0-beta01 or above. If there are major changes in AGP 7.0 we might drop support for AGP 4 at some point.

I'll prioritize this and hopefully land this before Christmas.

**Comment by Wrywulf** [comment]
I guess it was my turn to procrastinate :)

The tag pattern we are using is:
`<maj>.<min>.<patch>[-<pre-release version>]+<app identifier>`

Examples of tags:
```
1.5.8+appA
2.29.0-RC01+testApp
10.87.9-alpha04+old-app
```

The basic git describe glob pattern I'm applying right now is ie:
`git describe --match "[0-9]*.[0-9]*.[0-9]*+old-app"`

But basically I'm just looking for filtering on the app identifier so this would be enough:
`git describe --match "*+old-app"`

Let me know if it helps out.
